"""employee table

Revision ID: f204da2d7525
Revises: 7cec2a5efcfb
Create Date: 2020-02-17 17:46:40.840638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f204da2d7525'
down_revision = '7cec2a5efcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employeeid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('ProductGroup', sa.String(length=64), nullable=True),
    sa.Column('Level2', sa.String(length=64), nullable=True),
    sa.Column('Level3', sa.String(length=64), nullable=True),
    sa.Column('RTStart', sa.DateTime(), nullable=True),
    sa.Column('SectorRank', sa.String(length=4), nullable=True),
    sa.Column('SectorRanknew', sa.String(length=4), nullable=True),
    sa.Column('SectorRankfinal', sa.String(length=4), nullable=True),
    sa.Column('Comments', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_employeeid'), 'employee', ['employeeid'], unique=True)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_employeeid'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
